local citation = require("lifemode.domain.citation")

describe("parse_citations", function()
	it("parses single citation", function()
		local result = citation.parse_citations("See @smith2020 for details.")
		assert.equals(1, #result)
		assert.equals("bibtex", result[1].scheme)
		assert.equals("smith2020", result[1].key)
		assert.equals("@smith2020", result[1].raw)
		assert.is_nil(result[1].location)
	end)

	it("parses multiple citations", function()
		local result = citation.parse_citations("@smith2020 and @jones2021")
		assert.equals(2, #result)
		assert.equals("smith2020", result[1].key)
		assert.equals("jones2021", result[2].key)
	end)

	it("parses citations with underscores and hyphens", function()
		local result = citation.parse_citations("@smith_jones-2020")
		assert.equals(1, #result)
		assert.equals("smith_jones-2020", result[1].key)
	end)

	it("returns empty array for empty content", function()
		local result = citation.parse_citations("")
		assert.equals(0, #result)
	end)

	it("returns empty array for no citations", function()
		local result = citation.parse_citations("No citations here.")
		assert.equals(0, #result)
	end)

	it("returns empty array for invalid content type", function()
		local result = citation.parse_citations(nil)
		assert.equals(0, #result)
	end)

	it("parses citation at start of string", function()
		local result = citation.parse_citations("@first is the beginning")
		assert.equals(1, #result)
		assert.equals("first", result[1].key)
	end)

	it("parses citation at end of string", function()
		local result = citation.parse_citations("The end is @last")
		assert.equals(1, #result)
		assert.equals("last", result[1].key)
	end)

	it("parses adjacent citations", function()
		local result = citation.parse_citations("@one@two@three")
		assert.equals(3, #result)
		assert.equals("one", result[1].key)
		assert.equals("two", result[2].key)
		assert.equals("three", result[3].key)
	end)

	it("handles numbers in citation keys", function()
		local result = citation.parse_citations("@paper123 and @456data")
		assert.equals(2, #result)
		assert.equals("paper123", result[1].key)
		assert.equals("456data", result[2].key)
	end)

	it("stops at punctuation after citation", function()
		local result = citation.parse_citations("See @smith2020, and also @jones2021.")
		assert.equals(2, #result)
		assert.equals("smith2020", result[1].key)
		assert.equals("jones2021", result[2].key)
	end)

	it("does not match @ without identifier", function()
		local result = citation.parse_citations("Email me @ work")
		assert.equals(0, #result)
	end)

	it("does not match @ with spaces", function()
		local result = citation.parse_citations("@ smith2020")
		assert.equals(0, #result)
	end)
end)
